### ISSUE TITLE
Do you know yanic?

### ISSUE THREAD

**Issue by genofire** [Freifunk-Dresden/ViewerBackend#1]
[Yanic](https://github.com/FreifunkBremen/yanic) is really nice, it has support to write in `influxdb` and other database which could be render afterwards with grafana.

And works really well with [meshviewer](https://github.com/ffrgb/meshviewer) from regensburg - take a look at: https://meshviewer.org/.

Maybe you could create a fork a extra service like [meshviewer-collector](https://github.com/genofire/meshviewer-collector)

**Comment by hibo98** [comment]
No I didn't knew yanic before. And I think for Freifunk Dresden it is bit tricky to use tools like this because we don't use a gluon base firmware and all of the architecture is self constructed. 
For this I have to make several API requests and many translation that it works with hopglass and I'am working on it getting it running with meshviewer. I appreciate your work but I am not familiar with Go.

**Comment by genofire** [comment]
Great, i just once to inform you.
I try already to extract some things from gluon to openwrt for private use:
- https://github.com/freifunk-gluon/packages/pull/188
